### ISSUE TITLE
Cannot install Aderyn 

### ISSUE THREAD

**Issue by samtdomi** [Cyfrin/4-puppy-raffle-audit#11]
I have successfully installed rust and cargo - I get verification for both when running "--version" for each. However, I cannot successfully install aderyn - I keep getting these errors in the command line when running ``` cargo install aderyn ``` 

```
error: linker `cc` not found
  |
  = note: No such file or directory (os error 2)

error: could not compile `rayon-core` (build script) due to previous error
warning: build failed, waiting for other jobs to finish...
error: could not compile `serde` (build script) due to previous error
error: could not compile `crossbeam-utils` (build script) due to previous error
error: could not compile `proc-macro2` (build script) due to previous error
error: failed to compile `aderyn v0.0.12`, intermediate artifacts can be found at `/tmp/cargo-installg4LkPc`.
To reuse those artifacts with a future compilation, set the environment variable `CARGO_TARGET_DIR` to that path.

```

Any help is much appreciated.

**Comment by JDengin** [comment]
> I have successfully installed rust and cargo - I get verification for both when running "--version" for each. However, I cannot successfully install aderyn - I keep getting these errors in the command line when running `cargo install aderyn`
> 
> ```
> error: linker `cc` not found
>   |
>   = note: No such file or directory (os error 2)
> 
> error: could not compile `rayon-core` (build script) due to previous error
> warning: build failed, waiting for other jobs to finish...
> error: could not compile `serde` (build script) due to previous error
> error: could not compile `crossbeam-utils` (build script) due to previous error
> error: could not compile `proc-macro2` (build script) due to previous error
> error: failed to compile `aderyn v0.0.12`, intermediate artifacts can be found at `/tmp/cargo-installg4LkPc`.
> To reuse those artifacts with a future compilation, set the environment variable `CARGO_TARGET_DIR` to that path.
> ```
> 
> Any help is much appreciated.

I didn't encountered such an issue when installing Aderyn, It was the case with Slither. ChatGpt can help you fix the errors, what you have to do firstly is give it the context and secondly integrally copy and paste the errors you got in the command line. Good luck !

**Comment by JDengin** [comment]
> > I have successfully installed rust and cargo - I get verification for both when running "--version" for each. However, I cannot successfully install aderyn - I keep getting these errors in the command line when running `cargo install aderyn`
> > ```
> > error: linker `cc` not found
> >   |
> >   = note: No such file or directory (os error 2)
> > 
> > error: could not compile `rayon-core` (build script) due to previous error
> > warning: build failed, waiting for other jobs to finish...
> > error: could not compile `serde` (build script) due to previous error
> > error: could not compile `crossbeam-utils` (build script) due to previous error
> > error: could not compile `proc-macro2` (build script) due to previous error
> > error: failed to compile `aderyn v0.0.12`, intermediate artifacts can be found at `/tmp/cargo-installg4LkPc`.
> > To reuse those artifacts with a future compilation, set the environment variable `CARGO_TARGET_DIR` to that path.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Any help is much appreciated.
> 
> I didn't encountered such an issue when installing Aderyn, It was the case with Slither. ChatGpt can help you fix the errors, what you have to do in the same prompt is firstly give it the context and secondly integrally copy and paste the errors you got in the command line and give it that too. Good luck !

**Comment by S23Web3** [comment]
I tried to reproduce your issue to find the solution. Could you share your setup, windows/linux/mac and your install sequence?

**Comment by dhanesh24g** [comment]
> I have successfully installed rust and cargo - I get verification for both when running "--version" for each. However, I cannot successfully install aderyn - I keep getting these errors in the command line when running `cargo install aderyn`
> 
> ```
> error: linker `cc` not found
>   |
>   = note: No such file or directory (os error 2)
> 
> error: could not compile `rayon-core` (build script) due to previous error
> warning: build failed, waiting for other jobs to finish...
> error: could not compile `serde` (build script) due to previous error
> error: could not compile `crossbeam-utils` (build script) due to previous error
> error: could not compile `proc-macro2` (build script) due to previous error
> error: failed to compile `aderyn v0.0.12`, intermediate artifacts can be found at `/tmp/cargo-installg4LkPc`.
> To reuse those artifacts with a future compilation, set the environment variable `CARGO_TARGET_DIR` to that path.
> ```
> 
> Any help is much appreciated.

Dear @samtdomi ,

Please use below documentation to install Aderyn using cyfrinup.
Do make sure you uninstall the existing cargo based installation using `cargo uninstall aderyn` 

```hyperlink
https://github.com/Cyfrin/aderyn?tab=readme-ov-file#installing-aderyn
```

**Comment by PatrickAlphaC** [comment]
This should be fixed
