### ISSUE TITLE
make install throws errors after cloning the repo

### ISSUE THREAD

**Issue by S23Web3** [Cyfrin/4-puppy-raffle-audit#14]
Hi, the error returns that Tincho had opened prior.

Running on ubuntu and coming from the last password audit.
Cloned the repo

```
4-puppy-raffle-audit$ make install
forge install foundry-rs/forge-std --no-commit && forge install openzeppelin/openzeppelin-contracts@v3.4.0 --no-commit && forge install Brechtpd/base64 --no-commit 
Installing forge-std in /~/security-and-auditing/4-puppy-raffle-audit/lib/forge-std (url: Some("https://github.com/foundry-rs/forge-std"), tag: None)
fatal: 'lib/forge-std' already exists and is not a valid git repo
Error: 
git submodule exited with code 128
make: *** [Makefile:15: install] Error 1
```
There were three folders in the  lib, `base-64`, `forge-std` and `openzeppelin-contracts`, upon removing them and rerunning 
`make install` the errors disappeared.

**Comment by mooezz999** [comment]
Also after deleting '**lib**' folder trying to install everything single handedly instead of **"make install"**:
forge install foundry-rs/forge-std --no-commit 
forge install openzeppelin/openzeppelin-contracts@v3.4.0 --no-commit 
forge install Brechtpd/base64 --no-commit

**Comment by PatrickAlphaC** [comment]
Going to close, let me know if you still have this error

**Comment by mooezz999** [comment]
Sorry for the late reply. I already found the addresses in the page source.
