### ISSUE TITLE
"forge-std/Test.sol" not found after cloning and running make

### ISSUE THREAD

**Issue by 0xk3y** [Cyfrin/4-puppy-raffle-audit#5]
After cloning the repository and running make, I ran into the following issue when trying to code along in PuppyRaffle.t.sol 

Source "forge-std/Test.sol" not found: File outside of allowed directories.

Any ideas on how I might approach a fix?

<img width="544" alt="image" src="https://github.com/Cyfrin/4-puppy-raffle-audit/assets/141193328/8a51857b-2f54-4b35-b04c-6d446383a738">

For additional context, I believe the error I am getting may stem from the Test.sol file but not completely sure.

Source "ds-test/test.sol" not found: File not found.

<img width="731" alt="image" src="https://github.com/Cyfrin/4-puppy-raffle-audit/assets/141193328/a729436e-219c-4f16-b74b-cbc778e90aaf">

**Comment by Kentrell-K** [comment]
I got it working by manually adding ds-test to the .gitmodules folder. Testing seems to work for now but any ideas if this will mess things up later on down the line?

<img width="450" alt="image" src="https://github.com/Cyfrin/4-puppy-raffle-audit/assets/141193328/b6ef74c4-98eb-4b6a-8899-adaf78d8e0b4">

As shown below, this isn't included in the [Repo](https://github.com/Cyfrin/4-puppy-raffle-audit/blob/main/.gitmodules) but testing still worked for Patrick without it included in .gitmodules. Maybe this will help others with the same issue.
<img width="553" alt="image" src="https://github.com/Cyfrin/4-puppy-raffle-audit/assets/141193328/1fabd030-69a1-44e7-99b7-3708742ad5a1">

**Comment by PatrickAlphaC** [comment]
Hmm. I'm not able to reproduce your issue. I'm going to close for now.
