### ISSUE TITLE
Markdown report is empty when running aderyn .

### ISSUE THREAD

**Issue by 0xmaurice** [Cyfrin/4-puppy-raffle-audit#6]
When running `aderyn .` in my root folder, the report doesn't show any issues. 
```bash
$ aderyn .
Detecting framework...
Framework detected: Foundry mode engaged.
Foundry root path: "."
[⠢] Compiling...
[⠔] Compiling 3 files with 0.7.6
[⠒] Solc 0.7.6 finished in 2.42s
Compiler run successful with warnings:
Warning (2462): Visibility for constructor is ignored. If you want the contract to be non-deployable, making it "abstract" is sufficient.
    constructor () internal {
    ^ (Relevant source part starts here and spans across multiple lines).
Warning (2462): Visibility for constructor is ignored. If you want the contract to be non-deployable, making it "abstract" is sufficient.
    constructor () internal {
    ^ (Relevant source part starts here and spans across multiple lines).
Warning (2462): Visibility for constructor is ignored. If you want the contract to be non-deployable, making it "abstract" is sufficient.
    constructor (string memory name_, string memory symbol_) public {
    ^ (Relevant source part starts here and spans across multiple lines).
Warning (2072): Unused local variable.
        PuppyRaffle puppyRaffle = new PuppyRaffle(
        ^---------------------^
Get Detectors
Running 17 detectors
Detectors run, processing found issues
Found issues processed. Printing report
Report printed to ./report.md
```

Here is the my `report.md` file:

# Aderyn Analysis Report

This report was generated by [Aderyn](https://github.com/Cyfrin/aderyn), a static analysis tool built by [Cyfrin](https://cyfrin.io), a blockchain security company. This report is not a substitute for manual audit or security review. It should not be relied upon for any purpose other than to assist in the identification of potential security vulnerabilities.
# Table of Contents

- [Summary](#summary)
  - [Files Summary](#files-summary)
  - [Files Details](#files-details)
  - [Issue Summary](#issue-summary)

# Summary

## Files Summary

| Key | Value |
| --- | --- |
| .sol Files | 0 |
| Total nSLOC | 143 |

## Files Details

| Filepath | nSLOC |
| --- | --- |
| **Total** | **143** |

## Issue Summary

| Category | No. of Issues |
| --- | --- |
| Critical | 0 |
| High | 0 |
| Medium | 0 |
| Low | 0 |
| NC | 0 |

What am I doing wrong, what am I missing?(running `slither .` works fine)

Thanks for helping!

**Comment by Saswankar1** [comment]
The aderyn tool appears to have completed its analysis and produced a report indicating that there are no critical, high, medium, or low issues found in your Solidity files. The warnings shown in the console output are from the Solidity compiler (solc) and not from aderyn itself. These warnings are about visibility for constructors being ignored and an unused local variable.

It's important to note that static analysis tools like aderyn or slither are designed to detect known patterns that could potentially be vulnerabilities or code quality issues. The absence of reported issues in aderyn means that the tool did not find any such patterns in your code that match its detection rules. This doesn't necessarily mean that your code is free from vulnerabilities, but rather that none were identified by the specific rules and detectors used by aderyn.

Also manually review the code once

**Comment by i3arba** [comment]
Hey!
The same happens here. But in the video, when Collins used it, Aderyn showed some vulnerabilities in report.md file.

**Comment by PatrickAlphaC** [comment]
Going to close this, it looks like this was an aderyn bug but it's fixed now!
