### ISSUE TITLE
Commit hash in readme should be latest

### ISSUE THREAD

**Issue by rube-de** [Cyfrin/4-puppy-raffle-audit#7]
If you follow the instructions, stop the video and check the repo out yourself before continuing, the common behaviour would be to do it like how you learned it in Section 3. 
=> You checkout the commit hash from the onboarding.

If doing so, you won't have the slither config in your checked out code. 
=> The scope should be updated to the latest commit hash.

**Comment by PatrickAlphaC** [comment]
Technically that'll never be possible, since as long as the README needs to be the latest hash, every time you update the readme you'll get a new hash :) 

But I've updated!
